/**
 * Static collection of pattern-based puzzles used in the TakeNeuroIQ game.
 * Each puzzle object contains:
 * - id: Unique identifier
 * - title: Display title or instructions
 * - difficulty: First-pass challenge tier (easy, medium, hard)
 * - grid: 3x3 array of shapes with one 'missing' slot
 * - choices: Available shape options for the user
 * - correctAnswer: The shape that correctly completes the grid
 */
const patternPuzzles = [
  {
    id: 1,
    difficulty: 'easy',
    title: 'Identify the missing pattern',
    grid: [
      'square',
      'triangle',
      'circle',
      'triangle',
      'circle',
      'square',
      'circle',
      'missing',
      'triangle',
    ],
    choices: ['square', 'triangle', 'circle', 'bolt'],
    correctAnswer: 'square',
  },
  {
    id: 2,
    difficulty: 'easy',
    title: 'Find the missing symbol',
    grid: [
      'circle',
      'cross',
      'triangle',
      'cross',
      'triangle',
      'circle',
      'triangle',
      'missing',
      'cross',
    ],
    choices: ['cross', 'circle', 'triangle', 'square'],
    correctAnswer: 'circle',
  },
  {
    id: 3,
    difficulty: 'easy',
    title: 'Complete the sequence grid',
    grid: [
      'triangle',
      'square',
      'bolt',
      'square',
      'bolt',
      'triangle',
      'bolt',
      'missing',
      'square',
    ],
    choices: ['triangle', 'circle', 'bolt', 'square'],
    correctAnswer: 'triangle',
  },
  {
    id: 4,
    difficulty: 'medium',
    title: 'Complete the rotating pattern',
    grid: [
      'triangle',
      'square',
      'bolt',
      'square',
      'bolt',
      'triangle',
      'bolt',
      'triangle',
      'missing',
    ],
    choices: ['square', 'triangle', 'circle', 'bolt'],
    correctAnswer: 'bolt',
  },
  {
    id: 5,
    difficulty: 'medium',
    title: 'Identify the pattern',
    grid: [
      'bolt',
      'circle',
      'square',
      'circle',
      'square',
      'bolt',
      'square',
      'missing',
      'circle',
    ],
    choices: ['bolt', 'circle', 'square', 'triangle'],
    correctAnswer: 'bolt',
  },
  {
    id: 6,
    difficulty: 'medium',
    title: 'Complete the sequence',
    grid: [
      'circle',
      'triangle',
      'bolt',
      'triangle',
      'bolt',
      'circle',
      'bolt',
      'circle',
      'missing',
    ],
    choices: ['circle', 'triangle', 'bolt', 'square'],
    correctAnswer: 'triangle',
  },
  {
    id: 7,
    difficulty: 'hard',
    title: 'Shape Grid',
    grid: [
      'bolt',
      'square',
      'circle',
      'square',
      'circle',
      'bolt',
      'circle',
      'bolt',
      'missing',
    ],
    choices: ['bolt', 'square', 'circle', 'triangle'],
    correctAnswer: 'square',
  },
  {
    id: 8,
    difficulty: 'hard',
    title: 'Complete the pattern',
    grid: [
      'square',
      'triangle',
      'bolt',
      'triangle',
      'bolt',
      'square',
      'bolt',
      'missing',
      'triangle',
    ],
    choices: ['square', 'triangle', 'circle', 'bolt'],
    correctAnswer: 'square',
  },
  {
    id: 9,
    difficulty: 'hard',
    title: 'Final logic puzzle',
    grid: [
      'circle',
      'bolt',
      'triangle',
      'bolt',
      'triangle',
      'circle',
      'triangle',
      'circle',
      'missing',
    ],
    choices: ['circle', 'triangle', 'bolt', 'square'],
    correctAnswer: 'bolt',
  },
  {
    id: 10,
    difficulty: 'easy',
    title: 'Find the Circle',
    grid: [
      'square',
      'square',
      'square',
      'triangle',
      'triangle',
      'triangle',
      'circle',
      'missing',
      'circle',
    ],
    choices: ['circle', 'square', 'triangle', 'bolt'],
    correctAnswer: 'circle',
  },
  {
    id: 11,
    difficulty: 'medium',
    title: 'Complete the Circle sequence',
    grid: [
      'circle',
      'triangle',
      'square',
      'triangle',
      'square',
      'circle',
      'square',
      'circle',
      'missing',
    ],
    choices: ['circle', 'square', 'triangle', 'bolt'],
    correctAnswer: 'triangle',
  },
  {
    id: 12,
    difficulty: 'hard',
    title: 'Master Circle Pattern',
    grid: [
      'bolt',
      'circle',
      'square',
      'circle',
      'square',
      'bolt',
      'square',
      'bolt',
      'missing',
    ],
    choices: ['circle', 'square', 'triangle', 'bolt'],
    correctAnswer: 'circle',
  },
];

export default patternPuzzles;
