const patternPuzzles = [
  {
    id: 1,
    title: "Identify the missing pattern",
    grid: [
      "square",
      "triangle",
      "circle",
      "triangle",
      "circle",
      "square",
      "circle",
      "missing",
      "triangle",
    ],
    choices: ["square", "triangle", "circle", "diamond"],
    correctAnswer: "square",
  },
  {
    id: 2,
    title: "Find the missing symbol",
    grid: [
      "circle",
      "diamond",
      "triangle",
      "diamond",
      "triangle",
      "circle",
      "triangle",
      "missing",
      "diamond",
    ],
    choices: ["diamond", "circle", "triangle", "square"],
    correctAnswer: "circle",
  },
  {
    id: 3,
    title: "Complete the sequence grid",
    grid: [
      "triangle",
      "square",
      "diamond",
      "square",
      "diamond",
      "triangle",
      "diamond",
      "missing",
      "square",
    ],
    choices: ["triangle", "circle", "diamond", "square"],
    correctAnswer: "triangle",
  },
  {
    id: 4,
    title: "Complete the rotating pattern",
    grid: [
      "triangle",
      "square",
      "diamond",
      "square",
      "diamond",
      "triangle",
      "diamond",
      "triangle",
      "missing",
    ],
    choices: ["square", "triangle", "circle", "diamond"],
    correctAnswer: "diamond",
  },
  {
    id: 5,
    title: "Identify the pattern",
    grid: [
      "diamond",
      "circle",
      "square",
      "circle",
      "square",
      "diamond",
      "square",
      "missing",
      "circle",
    ],
    choices: ["diamond", "circle", "square", "triangle"],
    correctAnswer: "diamond",
  },
  {
    id: 6,
    title: "Complete the sequence",
    grid: [
      "circle",
      "triangle",
      "diamond",
      "triangle",
      "diamond",
      "circle",
      "diamond",
      "circle",
      "missing",
    ],
    choices: ["circle", "triangle", "diamond", "square"],
    correctAnswer: "triangle",
  },
  {
    id: 7,
    title: "Shape Grid",
    grid: [
      "diamond",
      "square",
      "circle",
      "square",
      "circle",
      "diamond",
      "circle",
      "diamond",
      "missing",
    ],
    choices: ["diamond", "square", "circle", "triangle"],
    correctAnswer: "square",
  },
  {
    id: 8,
    title: "Complete the pattern",
    grid: [
      "square",
      "triangle",
      "diamond",
      "triangle",
      "diamond",
      "square",
      "diamond",
      "missing",
      "triangle",
    ],
    choices: ["square", "triangle", "circle", "diamond"],
    correctAnswer: "square",
  },
  {
    id: 9,
    title: "Final logic puzzle",
    grid: [
      "circle",
      "diamond",
      "triangle",
      "diamond",
      "triangle",
      "circle",
      "triangle",
      "circle",
      "missing",
    ],
    choices: ["circle", "triangle", "diamond", "square"],
    correctAnswer: "diamond",
  },
];

export default patternPuzzles;
