import { test } from 'node:test';
import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
test('competition: server authority, privacy, retries, expiry, daily limits and settlement', async () => {
  const db = new PGlite();
  const ids = ['11111111-1111-4111-8111-111111111111', '22222222-2222-4222-8222-222222222222', '33333333-3333-4333-8333-333333333333'];
  await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key, raw_user_meta_data jsonb);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);
  for (const file of ['202609180001_accounts_and_scores.sql', '202609190001_competition.sql', '202609190002_question_clock.sql']) await db.exec(fs.readFileSync(new URL('../supabase/migrations/' + file, import.meta.url), 'utf8'));
  await db.exec(`insert into auth.users values ${ids.map((id, i) => `('${id}','{"display_name":"Player ${i}"}')`).join(',')};`);
  const as = async i => db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${ids[i]}',false)`);
  const rpc = async (sql, args = []) => (await db.query('select ' + sql + ' as data', args)).rows[0].data;
  const admin = async sql => {
    await db.exec('reset role');
    return db.query(sql);
  };
  await as(0);
  let m = await rpc("public.competition_start('friend')");
  assert.equal(m.status, 'waiting');
  assert.equal(m.question, null);
  assert.equal((await rpc("public.competition_start('friend')")).id, m.id);
  await assert.rejects(db.query('select * from neuro_private.matches'));
  await assert.rejects(rpc('neuro_private.make_questions(8)'));
  await as(2);
  await assert.rejects(rpc('public.competition_snapshot($1,true)', [m.id]));
  await as(1);
  m = await rpc("public.competition_start('friend',$1)", [m.code]);
  assert.equal(m.status, 'active');
  assert.ok(m.question);
  assert.equal(m.question.answer, undefined);
  assert.equal(m.question.explanation, undefined);
  await assert.rejects(rpc('public.competition_answer($1,1,0)', [m.id]));
  await assert.rejects(rpc('public.competition_answer($1,0,99)', [m.id]));
  const qs = (await admin(`select questions from neuro_private.matches where id='${m.id}'`)).rows[0].questions;
  await as(1);
  let answer = await rpc('public.competition_answer($1,0,$2)', [m.id, qs[0].answer]);
  assert.equal(answer.correct, true);
  const idle = await rpc('public.competition_state($1)', [m.id]);
  assert.equal(idle.question, null);
  assert.equal(idle.question_deadline, null);
  const retry = await rpc('public.competition_answer($1,0,$2)', [m.id, qs[0].answer]);
  assert.equal(retry.position, 1);
  assert.ok(retry.score <= 150 && retry.score >= 100);
  await rpc('public.competition_snapshot($1,true)', [m.id]);
  await admin(`update neuro_private.entries set question_started=clock_timestamp()-interval '31 seconds' where match_id='${m.id}' and player='${ids[1]}'`);
  await as(1);
  answer = await rpc('public.competition_answer($1,1,$2)', [m.id, qs[1].answer]);
  assert.equal(answer.correct, false);
  assert.equal(answer.points, 0);
  for (let i = 2; i < 8; i++) {
    await rpc('public.competition_snapshot($1,true)', [m.id]);
    await rpc('public.competition_answer($1,$2,$3)', [m.id, i, qs[i].answer]);
  }
  m = await rpc('public.competition_snapshot($1,true)', [m.id]);
  assert.equal(m.finished, true);
  assert.equal(m.status, 'active');
  assert.deepEqual(m.review, []);
  await as(0);
  await rpc('public.competition_snapshot($1,true)', [m.id]);
  await rpc('public.competition_leave($1)', [m.id]);
  await as(1);
  m = await rpc('public.competition_snapshot($1,true)', [m.id]);
  assert.equal(m.status, 'complete');
  assert.equal(m.outcome, 'win');
  assert.equal(m.rating_delta, 0);
  assert.equal(m.review.length, 8);
  let dashboard = await rpc('public.competition_dashboard()');
  assert.equal(dashboard.stats.games, 1);
  assert.equal(dashboard.stats.wins, 1);
  await rpc('public.competition_snapshot($1,true)', [m.id]);
  assert.equal((await rpc('public.competition_dashboard()')).stats.xp, dashboard.stats.xp);
  assert.deepEqual(await rpc("public.competition_leaderboard('rating')"), []);
  await db.exec('update public.profiles set leaderboard_opt_in=true');
  assert.deepEqual(await rpc("public.competition_leaderboard('rating')"), []);
  const board = await rpc("public.competition_leaderboard('week')");
  assert.equal(board.length, 1);
  assert.equal(board[0].email, undefined);
  assert.equal(board[0].player, undefined);
  await db.exec('update public.profiles set leaderboard_opt_in=false');
  assert.deepEqual(await rpc("public.competition_leaderboard('rating')"), []);
  let daily = await rpc("public.competition_start('daily')");
  assert.equal(daily.total, 10);
  await rpc('public.competition_leave($1)', [daily.id]);
  assert.equal((await rpc("public.competition_start('daily')")).id, daily.id);
  // Ranked win uses persisted results and changes both ratings once.
  await as(0);
  let ranked = await rpc("public.competition_start('ranked')");
  await as(1);
  ranked = await rpc("public.competition_start('ranked')");
  assert.equal(ranked.status, 'active');
  const rankedQs = (await admin(`select questions from neuro_private.matches where id='${ranked.id}'`)).rows[0].questions;
  await as(1);
  await rpc('public.competition_answer($1,0,$2)', [ranked.id, rankedQs[0].answer]);
  await rpc('public.competition_leave($1)', [ranked.id]);
  await admin(`update neuro_private.matches set expires_at=clock_timestamp()-interval '1 second' where id='${ranked.id}'`);
  await as(0);
  ranked = await rpc('public.competition_snapshot($1,true)', [ranked.id]);
  assert.equal(ranked.status, 'complete');
  assert.equal(ranked.rating_delta, -16);
  await as(1);
  assert.equal((await rpc('public.competition_snapshot($1,true)', [ranked.id])).rating_delta, 16);
  await db.exec('set role anon');
  await assert.rejects(rpc("public.competition_start('ranked')"));
  assert.ok(Array.isArray(await rpc("public.competition_leaderboard('daily')")));
  await db.close();
});
