// src/config/puzzleDevFlags.js

export const PUZZLE_DEV_FLAGS = {
  SHOW_PATTERN_RUSH_ANSWERS: true,
  SHOW_SEQUENCE_SPRINT_ANSWERS: true,
  SHOW_PUZZLE_DEBUG_META: true,
  SHOW_GRID_RECALL_ANSWERS: true,
  SHOW_LOGIC_GATE_ANSWERS: true,
  SHOW_SIGNAL_PATH_ANSWERS: true,
};